[build-system]
requires = [
  "numpy<2.0; python_version<'3.9'",
  # NumPy >=1.25 defaults to exposing "an API that is backwards compatible with the oldest NumPy version that supports the currently oldest compatible Python version"
  # https://numpy.org/devdocs/dev/depending_on_numpy.html#adding-a-dependency-on-numpy
  "numpy>=2.0; python_version>='3.9'",
  "packaging",
  "pip",
  "scikit-build>=0.14.0",
  "setuptools==59.2.0; python_version<'3.12'",
  "setuptools<70.0.0; python_version>='3.12'",
]
# use a custom backend to manage CMake check / installation
# see https://scikit-build.readthedocs.io/en/latest/usage.html#adding-cmake-as-building-requirement-only-if-not-installed-or-too-low-a-version
build-backend = "backend"
backend-path = ["_build_backend"]
