from setuptools import setup
from setuptools.dist import Distribution
import pip
import os
import sys

# cv_version.py should be generated by running find_version.py
from cv_version import opencv_version

numpy_version = ""

# Get required numpy version
for package in pip.get_installed_distributions():
    if package.key == "numpy":
        numpy_version = package.version

class BinaryDistribution(Distribution):
    """ Forces BinaryDistribution. """
    def has_ext_modules(self):
        return True

    def is_pure(self):
        return False

package_data = {}

if os.name == 'posix':
    package_data['cv2'] = ['*.so']
else:
    package_data['cv2'] = ['*.pyd']

setup(name='opencv-python',
      version=opencv_version,
      description='OpenCV',
      distclass=BinaryDistribution,
      packages=['cv2'],
      package_data=package_data,
      include_package_data=True,
      install_requires="numpy==%s" % numpy_version,
      )