SET(CMAKE_SYSTEM_NAME Darwin)
SET(CMAKE_SYSTEM_VERSION 16)
SET(CMAKE_SYSTEM_PROCESSOR x86_64)
SET(ARCH x86_64)

set(CMAKE_C_COMPILER gcc)
set(CMAKE_C_COMPILER_TARGET ${arch})
set(CMAKE_CXX_COMPILER g++)
set(CMAKE_CXX_COMPILER_TARGET ${arch})