name: macOS x86_64

on:
  pull_request:
    branches:
      - 4.x
      - 5.x
    paths-ignore:
      - '.github/workflows/build_wheels_manylinux*'
      - '.github/workflows/build_wheels_windows*'
      - '.github/workflows/build_wheels_macos_m1.yml'
      - '.github/workflows/build_sdist.yml'
      - '.github/workflows/release.yml'
  workflow_call:
    inputs:
      rolling:
        type: boolean
        default: false
  workflow_dispatch:

permissions:
  contents: read

jobs:
  Build:
    runs-on: macos-15-intel
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9']
        platform: [x64]
        with_contrib: [0, 1]
        without_gui: [0, 1]
        build_sdist: [0]
    env:
      CI_BUILD: 1
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      REPO_DIR: .
      PROJECT_SPEC: opencv-python
      MB_PYTHON_VERSION: ${{ matrix.python-version }}
      TRAVIS_PYTHON_VERSION: ${{ matrix.python-version }}
      MB_ML_VER: 2014
      TRAVIS_BUILD_DIR: ${{ github.workspace }}
      TRAVIS_OS_NAME: osx
      CONFIG_PATH: travis_config.sh
      USE_CCACHE: 1
      UNICODE_WIDTH: 32
      PLAT: x86_64
      SDIST: ${{ matrix.build_sdist || 0 }}
      ENABLE_HEADLESS: ${{ matrix.without_gui }}
      ENABLE_CONTRIB: ${{ matrix.with_contrib }}
      PIP_INDEX_URL: https://pypi.tuna.tsinghua.edu.cn/simple
    steps:
    - name: Setup environment
      if: inputs.rolling == 'true' || github.event_name == 'workflow_dispatch'
      run: |
        echo "ENABLE_ROLLING=1" >> $GITHUB_ENV
    - name: Checkout
      uses: actions/checkout@v7
      with:
        submodules: false
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v7
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.platform }}
    - name: Build a package
      run: |
        git submodule update --init multibuild
        echo $ENABLE_CONTRIB > contrib.enabled
        echo $ENABLE_HEADLESS > headless.enabled
        export MACOSX_DEPLOYMENT_TARGET=14.0
        python -m pip install toml && python -c 'import toml; c = toml.load("pyproject.toml"); print("\n".join(c["build-system"]["requires"]))' | python -m pip install -r /dev/stdin
        python setup.py bdist_wheel --py-limited-api=cp37 --dist-dir=wheelhouse -v
        delocate-wheel ${{ github.workspace }}/wheelhouse/opencv*
    - name: Saving a wheel accordingly to matrix
      uses: actions/upload-artifact@v7
      with:
        name: build-${{ matrix.platform }}-macos-${{ matrix.with_contrib }}-${{ matrix.without_gui }}-${{ matrix.build_sdist }}
        path: wheelhouse/opencv*.whl

  Test:
    needs: [Build]
    runs-on: macos-26-intel
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11', '3.12', '3.13', '3.14']
        platform: [x64]
        with_contrib: [0, 1]
        without_gui: [0, 1]
        build_sdist: [0]
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      MB_PYTHON_VERSION: ${{ matrix.python-version }}
      NP_TEST_DEP: numpy==1.19.4
      NP_TEST_DEP_LATEST: numpy==2.2.6
      CONFIG_PATH: travis_config.sh
      PLAT: x86_64
      OPENCV_TEST_DATA_PATH: ${{ github.workspace }}/opencv_extra/testdata
      PYLINT_TEST_FILE: ${{ github.workspace }}/opencv/samples/python/squares.py
      PIP_INDEX_URL: https://pypi.tuna.tsinghua.edu.cn/simple
    steps:
    - name: Cleanup
      run: find . -mindepth 1 -delete
      working-directory: ${{ github.workspace }}
    - name: Checkout
      uses: actions/checkout@v7
      with:
        submodules: true
        fetch-depth: 0
    - name: Download a wheel accordingly to matrix
      uses: actions/download-artifact@v8
      with:
        name: build-${{ matrix.platform }}-macos-${{ matrix.with_contrib }}-${{ matrix.without_gui }}-${{ matrix.build_sdist }}
        path: wheelhouse/
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v7
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.platform }}
    - name: Create Venv for test
      run: |
        test -d "${{ github.workspace }}/opencv_test" && rm -rf "${{ github.workspace }}/opencv_test"
        python -m venv ${{ github.workspace }}/opencv_test
    - name: Package installation
      run: |
        source ${{ github.workspace }}/opencv_test/bin/activate
        python -m pip install --upgrade pip
        python -m pip install --no-cache --force-reinstall wheelhouse/opencv*.whl
        cd ${{ github.workspace }}/tests
        python get_build_info.py
    - name: Run tests
      run: |
        source ${{ github.workspace }}/opencv_test/bin/activate
        cd ${{ github.workspace }}/opencv
        python modules/python/test/test.py -v --repo .
    - name: Pylint test
      run: |
        source ${{ github.workspace }}/opencv_test/bin/activate
        python -m pip install pylint==2.15.9
        cd ${{ github.workspace }}/tests
        python -m pylint $PYLINT_TEST_FILE
