name: Release

on:
  release:
    types: [published, edited]
  schedule:
    - cron: '0 3 * * 6'
  workflow_dispatch:


jobs:
  Build-manylinux:
    uses: $/.github/workflows/build_wheels_manylinux.yml # includes testing and sdist build
    with:
      enable-rolling: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}

  Build-windows:
    uses: $/.github/workflows/build_wheels_windows.yml # includes testing
    with:
      enable-rolling: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}

  Build-macosm1:
    uses: $/.github/workflows/build_wheels_macos_m1.yml # includes testing
    with:
      enable-rolling: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}

  Build-macos:
    uses: $/.github/workflows/build_wheels_macos.yml # includes testing
    with:
      enable-rolling: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}

  Release_rolling:
    if: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
    needs: [Build-manylinux, Build-windows, Build-macosm1, Build-macos]
    runs-on: ubuntu-22.04
    environment: opencv-python-rolling-release
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/download-artifact@v8
        with:
          path: wheelhouse/
      - name: Upload wheels for opencv_python_rolling
        run: |
          python -m pip install twine
          python -m twine upload -u ${{ secrets.OPENCV_PYTHON_ROLLING_USERNAME }} -p ${{ secrets.OPENCV_PYTHON_ROLLING_PASSWORD }} --skip-existing wheelhouse/wheel-*/opencv_python_rolling-*
      - name: Upload wheels for opencv_contrib_python_rolling
        run: |
          python -m pip install twine
          python -m twine upload -u ${{ secrets.OPENCV_CONTRIB_PYTHON_ROLLING_USERNAME }} -p ${{ secrets.OPENCV_CONTRIB_PYTHON_ROLLING_PASSWORD }} --skip-existing wheelhouse/wheel-*/opencv_contrib_python_rolling-*
      - name: Upload wheels for opencv_python_headless_rolling
        run: |
          python -m pip install twine
          python -m twine upload -u ${{ secrets.OPENCV_PYTHON_HEADLESS_ROLLING_USERNAME }} -p ${{ secrets.OPENCV_PYTHON_HEADLESS_ROLLING_PASSWORD }} --skip-existing wheelhouse/wheel-*/opencv_python_headless_rolling-*
      - name: Upload wheels for opencv_contrib_python_headless_rolling
        run: |
          python -m pip install twine
          python -m twine upload -u ${{ secrets.OPENCV_CONTRIB_PYTHON_HEADLESS_ROLLING_USERNAME }} -p ${{ secrets.OPENCV_CONTRIB_PYTHON_HEADLESS_ROLLING_PASSWORD }} --skip-existing wheelhouse/wheel-*/opencv_contrib_python_headless_rolling-*

  Pre-release:
    if: github.event_name == 'release' && github.event.release.prerelease
    needs: [Build-manylinux, Build-windows, Build-macosm1, Build-macos]
    runs-on: ubuntu-22.04
    environment: test-opencv-python-release
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/download-artifact@v8
        with:
          path: wheelhouse/
      - name: Upload all wheels
        run: |
          tree
          python -m pip install twine
          python -m twine upload --repository testpypi -u ${{ secrets.PYPI_USERNAME }} -p ${{ secrets.PYPI_PASSWORD }} --skip-existing wheelhouse/wheel-*/opencv_* wheelhouse/wheel-*/opencv-*

  Release:
    if: github.event_name == 'release' && !github.event.release.prerelease
    needs: [Build-manylinux, Build-windows, Build-macosm1, Build-macos]
    runs-on: ubuntu-22.04
    environment: opencv-python-release
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/download-artifact@v8
        with:
          path: wheelhouse/
      - name: Upload wheels for opencv_python
        run: |
          python -m pip install twine
          python -m twine upload -u ${{ secrets.OPENCV_PYTHON_USERNAME }} -p ${{ secrets.OPENCV_PYTHON_PASSWORD }} --skip-existing wheelhouse/wheel-*/opencv_python-* wheelhouse/wheel-*/opencv-python-[^h]* wheelhouse/opencv_python-* wheelhouse/opencv-python-[^h]*
      - name: Upload wheels for opencv_contrib_python
        run: |
          python -m pip install twine
          python -m twine upload -u ${{ secrets.OPENCV_CONTRIB_PYTHON_USERNAME }} -p ${{ secrets.OPENCV_CONTRIB_PYTHON_PASSWORD }} --skip-existing wheelhouse/wheel-*/opencv_contrib_python-* wheelhouse/wheel-*/opencv-contrib-python-[^h]* wheelhouse/opencv_contrib_python-* wheelhouse/opencv-contrib-python-[^h]*
      - name: Upload wheels for opencv_python_headless
        run: |
          python -m pip install twine
          python -m twine upload -u ${{ secrets.OPENCV_PYTHON_HEADLESS_USERNAME }} -p ${{ secrets.OPENCV_PYTHON_HEADLESS_PASSWORD }} --skip-existing wheelhouse/wheel-*/opencv_python_headless-* wheelhouse/wheel-*/opencv-python-headless-* wheelhouse/opencv_python_headless-* wheelhouse/opencv-python-headless-*
      - name: Upload wheels for opencv_contrib_python_headless
        run: |
          python -m pip install twine
          python -m twine upload -u ${{ secrets.OPENCV_CONTRIB_PYTHON_HEADLESS_USERNAME }} -p ${{ secrets.OPENCV_CONTRIB_PYTHON_HEADLESS_PASSWORD }} --skip-existing wheelhouse/wheel-*/opencv_contrib_python_headless-* wheelhouse/wheel-*/opencv-contrib-python-headless-* wheelhouse/opencv_contrib_python_headless-* wheelhouse/opencv-contrib-python-headless-*
